In [1]:
%cd ../../

%load_ext autoreload
%autoreload 2

/home/hoanghu/projects/Food-Waste-Optimization

In [2]:
import json

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

from src.services import model_service

In [4]:
model = model_service.ModelService()
# model.load_model()

2024-06-26 15:23:07.578 | INFO     | src.services.model_service:_load_arima:33 - Load trained ARIMA models for 3 restaurants

In [6]:
data = model.predict_occupancy()


print(json.dumps(data, indent=2, ensure_ascii=False))

[
  {
    "datetime": "2024-05-14 08:00:00",
    "600 Chemicum": 2.3504778928762917,
    "610 Physicum": 7.873081340058377,
    "620 Exactum": -3.807753916169986
  },
  {
    "datetime": "2024-05-14 09:00:00",
    "600 Chemicum": 0.42231769331290536,
    "610 Physicum": 16.790884421568023,
    "620 Exactum": -4.829608204622559
  },
  {
    "datetime": "2024-05-14 10:00:00",
    "600 Chemicum": 46.57567751539686,
    "610 Physicum": 25.799432100204854,
    "620 Exactum": 1.8698558715301488
  },
  {
    "datetime": "2024-05-14 11:00:00",
    "600 Chemicum": 267.5961603645516,
    "610 Physicum": 42.513380143008476,
    "620 Exactum": 128.5568072526379
  },
  {
    "datetime": "2024-05-14 12:00:00",
    "600 Chemicum": 317.7442158385561,
    "610 Physicum": 50.8487611867659,
    "620 Exactum": 117.47859994050384
  },
  {
    "datetime": "2024-05-14 13:00:00",
    "600 Chemicum": 137.45625916773042,
    "610 Physicum": 56.70820605740499,
    "620 Exactum": 62.86968014247918
  },
  {
    "datetime": "2024-05-14 14:00:00",
    "600 Chemicum": 91.95844142383157,
    "610 Physicum": 55.42343893954188,
    "620 Exactum": -0.5686526244243169
  },
  {
    "datetime": "2024-05-14 15:00:00",
    "600 Chemicum": 16.3001626050482,
    "610 Physicum": 29.289073172451936,
    "620 Exactum": 5.997982418319225
  },
  {
    "datetime": "2024-05-14 16:00:00",
    "600 Chemicum": 4.05853541813066,
    "610 Physicum": 20.8711974093942,
    "620 Exactum": -2.5226377146165078
  },
  {
    "datetime": "2024-05-15 08:00:00",
    "600 Chemicum": 4.062099259039435,
    "610 Physicum": 6.393381912537166,
    "620 Exactum": -8.569310402975816
  },
  {
    "datetime": "2024-05-15 09:00:00",
    "600 Chemicum": -0.33185060471564753,
    "610 Physicum": 12.053575023456801,
    "620 Exactum": -11.153133166807834
  },
  {
    "datetime": "2024-05-15 10:00:00",
    "600 Chemicum": 47.368582029733396,
    "610 Physicum": 23.881227051986173,
    "620 Exactum": 0.37752660329761056
  },
  {
    "datetime": "2024-05-15 11:00:00",
    "600 Chemicum": 255.98060858140917,
    "610 Physicum": 40.793755552008975,
    "620 Exactum": 119.90286294722534
  },
  {
    "datetime": "2024-05-15 12:00:00",
    "600 Chemicum": 303.0438145592051,
    "610 Physicum": 51.06197057705157,
    "620 Exactum": 113.29267117720008
  },
  {
    "datetime": "2024-05-15 13:00:00",
    "600 Chemicum": 136.6453350403259,
    "610 Physicum": 58.767513800564245,
    "620 Exactum": 58.768142841366966
  },
  {
    "datetime": "2024-05-15 14:00:00",
    "600 Chemicum": 86.31249536496608,
    "610 Physicum": 55.92906175891011,
    "620 Exactum": -5.548855944639854
  },
  {
    "datetime": "2024-05-15 15:00:00",
    "600 Chemicum": 20.795533562151526,
    "610 Physicum": 38.45553870710626,
    "620 Exactum": 1.3912732423056013
  },
  {
    "datetime": "2024-05-15 16:00:00",
    "600 Chemicum": 4.6177563449252474,
    "610 Physicum": 17.466943464875555,
    "620 Exactum": -6.8158048473563895
  },
  {
    "datetime": "2024-05-16 08:00:00",
    "600 Chemicum": 5.031207475544122,
    "610 Physicum": 2.03908864804788,
    "620 Exactum": -13.071235870674968
  },
  {
    "datetime": "2024-05-16 09:00:00",
    "600 Chemicum": -0.799880184338349,
    "610 Physicum": 7.65898035685683,
    "620 Exactum": -17.184533893654816
  },
  {
    "datetime": "2024-05-16 10:00:00",
    "600 Chemicum": 47.976580064462475,
    "610 Physicum": 20.39146751329872,
    "620 Exactum": -1.9467843770115678
  },
  {
    "datetime": "2024-05-16 11:00:00",
    "600 Chemicum": 245.1826317428273,
    "610 Physicum": 36.593715305453486,
    "620 Exactum": 111.81586457809681
  },
  {
    "datetime": "2024-05-16 12:00:00",
    "600 Chemicum": 289.61101167787393,
    "610 Physicum": 48.60257997556198,
    "620 Exactum": 109.0279737285108
  },
  {
    "datetime": "2024-05-16 13:00:00",
    "600 Chemicum": 135.5019859718771,
    "610 Physicum": 56.367083345496894,
    "620 Exactum": 54.23535762186157
  },
  {
    "datetime": "2024-05-16 14:00:00",
    "600 Chemicum": 81.58536961584764,
    "610 Physicum": 54.035756769230375,
    "620 Exactum": -10.25688353118403
  },
  {
    "datetime": "2024-05-16 15:00:00",
    "600 Chemicum": 24.367295663990554,
    "610 Physicum": 39.17187812974612,
    "620 Exactum": -3.166732779376389
  },
  {
    "datetime": "2024-05-16 16:00:00",
    "600 Chemicum": 5.182835314948214,
    "610 Physicum": 13.880009219052056,
    "620 Exactum": -11.514950837660535
  },
  {
    "datetime": "2024-05-17 08:00:00",
    "600 Chemicum": 5.978217113395651,
    "610 Physicum": -3.5813319858522163,
    "620 Exactum": -17.2589433642936
  },
  {
    "datetime": "2024-05-17 09:00:00",
    "600 Chemicum": -0.4958472176899775,
    "610 Physicum": 2.4570958607320676,
    "620 Exactum": -22.849426040654635
  },
  {
    "datetime": "2024-05-17 10:00:00",
    "600 Chemicum": 49.009595171843635,
    "610 Physicum": 15.387743326880866,
    "620 Exactum": -4.711053116575954
  },
  {
    "datetime": "2024-05-17 11:00:00",
    "600 Chemicum": 235.70833819239306,
    "610 Physicum": 31.119940045644057,
    "620 Exactum": 104.32257930981712
  },
  {
    "datetime": "2024-05-17 12:00:00",
    "600 Chemicum": 277.8723684096032,
    "610 Physicum": 44.008448758748955,
    "620 Exactum": 104.81568279228748
  },
  {
    "datetime": "2024-05-17 13:00:00",
    "600 Chemicum": 134.6894662998806,
    "610 Physicum": 51.747152777712415,
    "620 Exactum": 49.602320483428
  },
  {
    "datetime": "2024-05-17 14:00:00",
    "600 Chemicum": 78.18466315599449,
    "610 Physicum": 49.89767315574318,
    "620 Exactum": -14.625453316073617
  },
  {
    "datetime": "2024-05-17 15:00:00",
    "600 Chemicum": 27.75487863789993,
    "610 Physicum": 35.888706955207226,
    "620 Exactum": -7.552970099821209
  },
  {
    "datetime": "2024-05-17 16:00:00",
    "600 Chemicum": 6.258562794422474,
    "610 Physicum": 9.05965454856107,
    "620 Exactum": -16.30586636553096
  },
  {
    "datetime": "2024-05-20 08:00:00",
    "600 Chemicum": 18.50522121039618,
    "610 Physicum": 1.4960150410916526,
    "620 Exactum": -17.277509162570823
  },
  {
    "datetime": "2024-05-20 09:00:00",
    "600 Chemicum": 11.997174140738537,
    "610 Physicum": 7.837651276808003,
    "620 Exactum": -24.26929754854723
  },
  {
    "datetime": "2024-05-20 10:00:00",
    "600 Chemicum": 61.97639785614879,
    "610 Physicum": 20.77877032268748,
    "620 Exactum": -3.823813726934304
  },
  {
    "datetime": "2024-05-20 11:00:00",
    "600 Chemicum": 238.97700530994666,
    "610 Physicum": 36.26245130374764,
    "620 Exactum": 101.25422096704199
  },
  {
    "datetime": "2024-05-20 12:00:00",
    "600 Chemicum": 279.1812099192377,
    "610 Physicum": 49.53216352099895,
    "620 Exactum": 104.57753314238619
  },
  {
    "datetime": "2024-05-20 13:00:00",
    "600 Chemicum": 145.7578121840058,
    "610 Physicum": 57.29455871041114,
    "620 Exactum": 48.91067572231805
  },
  {
    "datetime": "2024-05-20 14:00:00",
    "600 Chemicum": 87.4555088319473,
    "610 Physicum": 55.710048768186596,
    "620 Exactum": -14.787948131146322
  },
  {
    "datetime": "2024-05-20 15:00:00",
    "600 Chemicum": 42.572518768330056,
    "610 Physicum": 42.00753271454818,
    "620 Exactum": -7.855672384610216
  },
  {
    "datetime": "2024-05-20 16:00:00",
    "600 Chemicum": 19.278562985244278,
    "610 Physicum": 14.60875266163481,
    "620 Exactum": -17.15754024808382
  }
]

## tuntidata2.xlsx

In [21]:
df = pd.read_excel("src/data/basic_mvp_data/tuntidata2.xlsx", index_col=0)

df.head()

            Kuitin tunti     Ravintola  Kuitti kpl
Date
2023-01-02             8  600 Chemicum           1
2023-01-02            10  600 Chemicum          18
2023-01-02            11  600 Chemicum          83
2023-01-02            12  600 Chemicum          79
2023-01-02            13  600 Chemicum          90

In [22]:
df = df.replace({
    "600 Chemicum": "Chemicum",
    "610 Physicum": "Physicum",
    "620 Exactum": "Exactum"
})

df["weekday"] = df.index.dayofweek

df.head()

            Kuitin tunti Ravintola  Kuitti kpl  weekday
Date
2023-01-02             8  Chemicum           1        0
2023-01-02            10  Chemicum          18        0
2023-01-02            11  Chemicum          83        0
2023-01-02            12  Chemicum          79        0
2023-01-02            13  Chemicum          90        0

In [ ]:
grouped_df = df.groupby(
    ["Ravintola", "weekday", "Kuitin tunti"]).mean().to_dict()["Kuitti kpl"]

restaurants = ["Chemicum", "Physicum", "Exactum"]

occupancy = {
    restaurant: {
        day: [
            grouped_df.get((restaurant, day, hour), 0)
            for hour in range(24)
        ]
        for day in range(7)
    }
    for restaurant in restaurants
}